name : a test workflow

on : 
    push: 
        branches: ["main"]

jobs: 
    testing-testing:
        runs-on: ubuntu-latest
        steps:
            # step 1 - under the jobs are
            - name: welcome people
              run: echo "welcome to class"
            # step 2
            - name: tell people goodbye
              run: echo"Thank you for coming! See you soon."
                



